name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  build-release:
    name: Build Release ${{ matrix.target }}
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: token-linux-amd64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            name: token-linux-arm64
          - os: macos-latest
            target: x86_64-apple-darwin
            name: token-macos-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            name: token-macos-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: token-windows-amd64.exe

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install cross (for cross-compilation)
        if: matrix.target != 'x86_64-unknown-linux-gnu' && matrix.target != 'x86_64-apple-darwin' && matrix.target != 'aarch64-apple-darwin' && matrix.target != 'x86_64-pc-windows-msvc'
        run: cargo install cross

      - name: Build Release
        run: |
          if [[ "${{ matrix.target }}" == "x86_64-unknown-linux-gnu" ]] || [[ "${{ matrix.target }}" == "x86_64-apple-darwin" ]] || [[ "${{ matrix.target }}" == "aarch64-apple-darwin" ]] || [[ "${{ matrix.target }}" == "x86_64-pc-windows-msvc" ]]; then
            cargo build --release --target ${{ matrix.target }}
          else
            cross build --release --target ${{ matrix.target }}
          fi
        shell: bash

      - name: Prepare Artifact
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp "target/${{ matrix.target }}/release/token.exe" "./${{ matrix.name }}"
          else
            cp "target/${{ matrix.target }}/release/token" "./${{ matrix.name }}"
          fi

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ matrix.name }}
          asset_name: ${{ matrix.name }}
          asset_content_type: application/octet-stream
